name = "analytics-cron"
main = "src/worker.ts"
compatibility_date = "2024-01-20"

# Cron Triggers
# Docs: https://developers.cloudflare.com/workers/platform/triggers/cron-triggers/
# Configuration: https://developers.cloudflare.com/workers/wrangler/configuration/#triggers
[triggers]
# run every 6 hours
crons = ["* * * * *"]

# If you are only using Pages + D1, you only need the below in your wrangler.toml to interact with D1 locally.
[[d1_databases]]
binding = "DB" # Should match preview_database_id
database_name = "alot-db"
database_id = "231d59eb-7986-4198-bb8e-3adcacc84afe" # wrangler d1 info YOUR_DATABASE_NAME
preview_database_id = "DB" # Required for Pages local development
migrations_dir = "database/migrations"


[vars]
ACCOUNT_IDENTIFIER = "6523e349bc2b3b61bc5155528f142bd7"
CF_API_KEY = "L9m03NbNPm8JAZ2-Sd3F4QlVhvl6pWzA-5IhHfaK"
ZONE_ID = "d128952c96a3e5558f8a80b17080ff1e"
SUPABASE_URL = "https://krznnysyzjybyrcbefqs.supabase.co"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtyem5ueXN5emp5YnlyY2JlZnFzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcwNDkzNjkyOCwiZXhwIjoyMDIwNTEyOTI4fQ.iFbBKaj-H6M4reNos05U7_hHu3gsWrk67tQ-miKXcA0"